from cellar.schemas.matchmaker import ModelTier, SeedModel

ZDHHC20_PDAC_PANEL: list[SeedModel] = [
    SeedModel(
        name="Patient-derived PDAC organoid (HUB/Hubrecht)",
        tier=ModelTier.ORGANOID,
        source="HUB Organoids / HCMI",
        mrna_expressed=0.85,
        protein_present=0.85,
        isoform_match=0.8,
        disease_features_match=0.9,
        dependency_signal=0.6,
        genetic_tractable=0.8,
        provenance_ok=1.0,
        prior_use=0.7,
        coexpression={"GOLGA7": 0.8, "KRAS": 0.9, "EGFR": 0.7},
    ),
    SeedModel(
        name="MIA PaCa-2 (KRAS G12C, 2D)",
        tier=ModelTier.TWO_D_LINE,
        source="ATCC CRL-1420",
        mrna_expressed=0.9,
        protein_present=0.7,
        isoform_match=0.7,
        disease_features_match=0.7,
        dependency_signal=0.5,
        genetic_tractable=0.95,
        provenance_ok=1.0,
        prior_use=0.5,
        coexpression={"GOLGA7": 0.6, "KRAS": 0.85, "EGFR": 0.5},
    ),
    SeedModel(
        name="PANC-1 (KRAS G12D, 2D)",
        tier=ModelTier.TWO_D_LINE,
        source="ATCC CRL-1469",
        mrna_expressed=0.8,
        protein_present=0.65,
        isoform_match=0.7,
        disease_features_match=0.7,
        dependency_signal=0.45,
        genetic_tractable=0.95,
        provenance_ok=1.0,
        prior_use=0.4,
        coexpression={"GOLGA7": 0.1, "KRAS": 0.8, "EGFR": 0.45},
    ),
    SeedModel(
        name="PDAC organoid + autologous T-cell co-culture",
        tier=ModelTier.COCULTURE,
        source="CRO-built (e.g. Crown Bio / Xilis)",
        mrna_expressed=0.85,
        protein_present=0.85,
        isoform_match=0.8,
        disease_features_match=0.85,
        dependency_signal=0.6,
        genetic_tractable=0.5,
        provenance_ok=1.0,
        prior_use=0.3,
        coexpression={"GOLGA7": 0.8, "KRAS": 0.85, "EGFR": 0.7},
        capability_overrides={"add_native": ["immune_compartment"]},
    ),
    SeedModel(
        name="KPC GEMM (LSL-KrasG12D;Trp53;Pdx1-Cre)",
        tier=ModelTier.IN_VIVO,
        source="JAX / CRO",
        mrna_expressed=0.9,
        protein_present=0.9,
        isoform_match=0.85,
        disease_features_match=0.95,
        dependency_signal=0.7,
        genetic_tractable=0.6,
        provenance_ok=1.0,
        prior_use=0.6,
        coexpression={"GOLGA7": 0.85, "KRAS": 0.95, "EGFR": 0.75},
    ),
    SeedModel(
        name="DHHC-truncated PDAC line (isoform w/o DHHC domain)",
        tier=ModelTier.TWO_D_LINE,
        source="(illustrative)",
        mrna_expressed=0.85,
        protein_present=0.6,
        isoform_match=0.05,
        disease_features_match=0.7,
        dependency_signal=0.2,
        genetic_tractable=0.9,
        provenance_ok=1.0,
        prior_use=0.1,
        coexpression={"GOLGA7": 0.8, "KRAS": 0.9, "EGFR": 0.7},
        catalytic_domain_ok=False,
    ),
]

_PANELS_BY_TARGET: dict[str, list[SeedModel]] = {"ZDHHC20": ZDHHC20_PDAC_PANEL}


def seed_panel_for(target_symbol: str) -> list[SeedModel] | None:
    return _PANELS_BY_TARGET.get(target_symbol.upper())
